CREATE TABLE SHOPPINGBAG_TB(
SB_NO  VARCHAR2(13 CHAR) PRIMARY KEY,
SB_CSMID  VARCHAR2(12 CHAR) NOT NULL,
SB_GDNO VARCHAR2(13 CHAR) NOT NULL,
SB_OPNO VARCHAR2(5) NOT NULL,
SB_QUANTITY NUMBER(3) NOT NULL
);

SELECT SB_NO, GD_NAME, GD_IMGM, OP_NAME, SB_QUANTITY, OP_PRICE, GD_PRICE FROM SHOPPINGBAG_TB, GOODS_TB, OPTION_TB WHERE 
GD_NO = SB_GDNO AND OP_NO = SB_OPNO and SB_CSMID = 'qqqqqqqq';

CREATE sequence SHOPPINGBAG_Seq;

drop sequence SHOPPINGBAG_tb_Seq;

insert into SHOPPINGBAG_TB values('8888444465666','qqqqqqqq','9998887774445','1',5);

ALTER TABLE SHOPPINGBAG_TB
ADD CONSTRAINTS FK_SB_CSMID FOREIGN KEY(SB_CSMID)
REFERENCES CUSTOMER_REG(CSM_ID);

ALTER TABLE SHOPPINGBAG_TB
ADD CONSTRAINTS FK_SB_GDNO FOREIGN KEY(SB_GDNO)
REFERENCES GOODS_TB(GD_NO);

ALTER TABLE SHOPPINGBAG_TB
ADD CONSTRAINTS FK_SB_OPNO FOREIGN KEY(SB_OPNO)
REFERENCES OPTION_TB(OP_NO);

select * from SHOPPINGBAG_TB;

